### ISSUE TITLE
Provide descriptive and understandable title, description and README

### ISSUE THREAD

**Issue by ziolek** [rstgroup/rst-connector#1]
Hey!

Can I ask you to **rename** the repository to make it more clear and understandable?
Take a look at another repository for the convention:

- xcode-project-template
- react-components-form

Check out this guide for more: https://open-source-guide.18f.gov/naming-your-project/

Also provide a descriptive, clear and concise repository **description**.
See: https://open-source-guide.18f.gov/writing-the-repo-description/

Don't forget about good **README** as soon as you are ready to fill it.

Thanks!

**Comment by tomek2312** [comment]
Hello.

I did my best to provide as many details as it's possible. The project is still in MVP stage so no evertyhing is already set.

**Comment by ziolek** [comment]
Great! Thanks
